stages:
  - deploy_staging
  - create_production_mr
#   - deploy_production

deploy_to_staging:
  stage: deploy_staging
  tags:
    - general
  script:
    - echo "Merged to staging branch"
    - echo "Place to add commands to deploy to production environment (can be done later)"
  only:
    - staging

create_production_merge_request:
  stage: create_production_mr
  tags:
    - general
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    - |
      curl -v \
        --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        --header "Content-Type: application/json" \
        --request POST \
        --data '{
          "source_branch": "staging",
          "target_branch": "main",
          "title": "Merge staging into production",
          "description": "This MR was automatically created to merge staging changes into production."
        }' \
  only:
    - staging

# deploy_to_production:
#   stage: deploy_production
#   script:
#     - echo "Deploying to production (main branch)"
#     - echo "Place to add commands to deploy to production environment (can be done later)"
#   when: manual
#   only:
#     - main

#comment added (testing pipeline) v2
